disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - ExpandableArrayTests
line_length: 120
function_body_length: 20
